### ISSUE TITLE
Build fails with `spawn neo4j-shell ENOENT`

### ISSUE THREAD

**Issue by ryanfb** [ryanfb/docker_histograph#2]
I think we need to install (but not run) neo4j inside the histograph container in order to get the `neo4j-shell` executable:

```
histograph_1     | RUNNING [data] => node index.js geonames tgn
histograph_1     | Processing dataset geonames:
histograph_1     |   Executing step download...
histograph_1     |     Done!
histograph_1     |   Executing step convert...
histograph_1     |     Done!
histograph_1     |   Executing step done...
histograph_1     |     Done!
histograph_1     | Processing dataset tgn:
histograph_1     |   Executing step download...
histograph_1     |     Done!
histograph_1     |   Executing step convert...
histograph_1     |     Done!
histograph_1     |   Executing step done...
histograph_1     |     Done!
histograph_1     |
histograph_1     | All datasets done!
histograph_1     | clear neo4j edges =>
histograph_1     | RUNNING => neo4j-shell -c match ()-[e]-() delete e;
histograph_1     | Error: spawn neo4j-shell ENOENT
histograph_1     |     at exports._errnoException (util.js:893:11)
histograph_1     |     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
histograph_1     |     at onErrorNT (internal/child_process.js:348:16)
histograph_1     |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
histograph_1     |     at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by ryanfb** [comment]
Fixed by a818f0b8875fc18abcf92b12a101e5f2df11168b
